//PRODUCTS
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const FETCH_PRODUCTS = ' FETCH_PRODUCTS';
export const FETCH_PRODUCTS_SUCCESS = ' FETCH_PRODUCTS_SUCCESS';

//AUTH
export const AUTH_LOADING = 'AUTH_LOADING';
export const CHECK_USER_TOKEN = 'CHECK_USER_TOKEN';
export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
//CART
export const LOAD_CART = 'LOAD_CART';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const UPDATE_CART = 'UPDATE_CART';
export const CHANGE_PRODUCT_QUANTITY = 'CHANGE_PRODUCT_QUANTITY';

//FILTERS
export const SET_FILTERS = 'SET_FILTERS';

//MESSAGES
export const SUCCESS_MESSAGE = 'SUCCESS_MESSAGE';
export const ERROR_MESSAGE = 'ERROR_MESSAGE';
export const INFO_MESSAGE = 'INFO_MESSAGE';
export const SET_MESSAGE = 'SET_MESSAGE';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';

//CHECKOUT
export const CREATE_CHECKOUT_SESSION = 'CREATE_CHECKOUT_SESSION';
export const CREATE_CHECKOUT_SESSION_SUCCESS = 'CREATE_CHECKOUT_SESSION_SUCCESS';

//MODAL
export const OPEN_CART = 'OPEN_CART';
export const CLOSE_CART = 'CLOSE_CART';
export const OPEN_CHECKOUT = 'OPEN_CHECKOUT';
export const CLOSE_CHECKOUT = 'CLOSE_CHECKOUT';
export const OPEN_CHECKOUT_SUCCESS = 'OPEN_CHECKOUT_SUCCESS';
export const CLOSE_CHECKOUT_SUCCESS = 'CLOSE_CHECKOUT_SUCCESS';
export const OPEN_CHECKOUT_ERROR = 'OPEN_CHECKOUT_ERROR';
export const CLOSE_CHECKOUT_ERROR = 'CLOSE_CHECKOUT_ERROR';
export const OPEN_DRAWER = 'OPEN_DRAWER';
export const CLOSE_DRAWER = 'CLOSE_DRAWER';
export const OPEN_FILTERS = 'OPEN_FILTERS';
export const CLOSE_FILTERS = 'CLOSE_FILTERS';
export const OPEN_LOGIN = 'OPEN_LOGIN';
export const CLOSE_LOGIN = 'CLOSE_LOGIN';
export const OPEN_PRODUCT_DETAILS = 'OPEN_PRODUCT_DETAILS';
export const CLOSE_PRODUCT_DETAILS = 'CLOSE_PRODUCT_DETAILS';

//??
export const SET_CUSTOMER_LIST = 'SET_CUSTOMER_LIST';
export const SET_CUSTOMER_LIST_ERROR = 'SET_CUSTOMER_LIST_ERROR';
