//PRODUCTS
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const FETCH_PRODUCTS = ' FETCH_PRODUCTS';
export const FETCH_PRODUCTS_SUCCESS = ' FETCH_PRODUCTS_SUCCESS';

//AUTH
export const AUTH_LOADING = 'AUTH_LOADING';
export const CHECK_USER_TOKEN = 'CHECK_USER_TOKEN';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR';
export const LOGOUT = 'LOGOUT';
export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';

//CART
export const LOAD_CART = 'LOAD_CART';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const UPDATE_CART = 'UPDATE_CART';
export const CHANGE_PRODUCT_QUANTITY = 'CHANGE_PRODUCT_QUANTITY';

//FILTERS
export const SET_FILTERS = 'SET_FILTERS';

//MESSAGES
export const SUCCESS_MESSAGE = 'SUCCESS_MESSAGE';
export const ERROR_MESSAGE = 'ERROR_MESSAGE';
export const INFO_MESSAGE = 'INFO_MESSAGE';
export const SET_MESSAGE = 'SET_MESSAGE';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';

//CHECKOUT
export const CREATE_CHECKOUT_SESSION = 'CREATE_CHECKOUT_SESSION';
export const CREATE_CHECKOUT_SESSION_SUCCESS = 'CREATE_CHECKOUT_SESSION_SUCCESS';

//MODAL
export const OPEN_CART_MODAL = 'OPEN_CART_MODAL';
export const CLOSE_CART_MODAL = 'CLOSE_CART_MODAL';
export const OPEN_CHECKOUT_MODAL = 'OPEN_CHECKOUT_MODAL';
export const CLOSE_CHECKOUT_MODAL = 'CLOSE_CHECKOUT_MODAL';
export const OPEN_CHECKOUT_MODAL_SUCCESS = 'OPEN_CHECKOUT_MODAL_SUCCESS';
export const CLOSE_OPEN_CHECKOUT_MODAL_SUCCESS = 'CLOSE_OPEN_CHECKOUT_MODAL_SUCCESS';
export const OPEN_CHECKOUT_MODAL_ERROR = 'OPEN_CHECKOUT_MODAL_ERROR';
export const CLOSE_CHECKOUT_MODAL_ERROR = 'CLOSE_CHECKOUT_MODAL_ERROR';
export const OPEN_DRAWER_MODAL = 'OPEN_DRAWER_MODAL';
export const CLOSE_DRAWER_MODAL = 'CLOSE_DRAWER_MODAL';
export const OPEN_FILTERS_MODAL = 'OPEN_FILTERS_MODAL';
export const CLOSE_FILTERS_MODAL = 'CLOSE_FILTERS_MODAL';
export const OPEN_LOGIN_MODAL = 'OPEN_LOGIN_MODAL';
export const CLOSE_LOGIN_MODAL = 'CLOSE_LOGIN_MODAL';
export const OPEN_PRODUCT_DETAILS_MODAL = 'OPEN_PRODUCT_DETAILS_MODAL';
export const CLOSE_PRODUCT_DETAILS_MODAL = 'CLOSE_PRODUCT_DETAILS_MODAL';
export const OPEN_USER_MODAL = 'OPEN_USER_MODAL';
export const CLOSE_USER_MODAL = 'CLOSE_USER_MODAL';

//USERS
export const FETCH_USER_DETAILS = 'FETCH_USER_DETAILS';
export const FETCH_USER_DETAILS_SUCCESS = 'FETCH_USER_DETAILS_SUCCESS';
export const FETCH_USER_DETAILS_ERROR = 'FETCH_USER_DETAILS_ERROR';
export const USER_DETAILS_LOADING = 'USER_DETAILS_LOADING';
//??
export const SET_CUSTOMER_LIST = 'SET_CUSTOMER_LIST';
export const SET_CUSTOMER_LIST_ERROR = 'SET_CUSTOMER_LIST_ERROR';
