//AUTH
export const LOGIN_WITH_GOOGLE = 'LOGIN_WITH_GOOGLE'
export const CHECK_USER_TOKEN = 'CHECK_USER_TOKEN'
export const LOGIN_USER = 'LOGIN_USER'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR'
export const LOGOUT = 'LOGOUT'
export const REGISTER_USER = 'REGISTER_USER'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR'
export const VALIDATE_EMAIL_IN_DB = 'VALIDATE_EMAIL_IN_DB'
export const VALIDATE_EMAIL_IN_DB_SUCCESS = 'VALIDATE_EMAIL_IN_DB_SUCCESS'
export const VALIDATE_EMAIL_IN_DB_ERROR = 'VALIDATE_EMAIL_IN_DB_ERROR'
export const REQUEST_PASSWORD_RECOVERY = 'REQUEST_PASSWORD_RECOVERY'
export const REQUEST_PASSWORD_RECOVERY_SUCCESS = 'REQUEST_PASSWORD_RECOVERY_SUCCESS'
export const REQUEST_PASSWORD_RECOVERY_ERROR = 'REQUEST_PASSWORD_RECOVERY_ERROR'
export const VALIDATE_TOKEN_FOR_PASSWORD_CHANGE = 'VALIDATE_TOKEN_FOR_PASSWORD_CHANGE'
export const VALIDATE_TOKEN_FOR_PASSWORD_CHANGE_SUCCESS =
  'VALIDATE_TOKEN_FOR_PASSWORD_CHANGE_SUCCESS'
export const VALIDATE_TOKEN_FOR_PASSWORD_CHANGE_ERROR = 'VALIDATE_TOKEN_FOR_PASSWORD_CHANGE_ERROR'
export const REQUEST_CHANGE_USER_PASSWORD = 'REQUEST_CHANGE_USER_PASSWORD'
export const REQUEST_CHANGE_USER_PASSWORD_SUCCESS = 'REQUEST_CHANGE_USER_PASSWORD_SUCCESS'
export const REQUEST_CHANGE_USER_PASSWORD_ERROR = 'REQUEST_CHANGE_USER_PASSWORD_ERROR'

//CART
export const LOAD_CART = 'LOAD_CART'
export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const UPDATE_CART = 'UPDATE_CART'
export const CHANGE_PRODUCT_QUANTITY = 'CHANGE_PRODUCT_QUANTITY'
export const CLEAR_CART = 'CLEAR_CART'

//CHECKOUT
export const CREATE_CHECKOUT_SESSION = 'CREATE_CHECKOUT_SESSION'
export const CREATE_CHECKOUT_SESSION_SUCCESS = 'CREATE_CHECKOUT_SESSION_SUCCESS'
export const CREATE_CHECKOUT_SESSION_ERROR = 'CREATE_CHECKOUT_SESSION_ERROR'

//EMAIL
export const SEND_CONTACT_FORM = 'SEND_CONTACT_FORM'
export const SEND_CONTACT_FORM_SUCCESS = 'SEND_CONTACT_FORM_SUCCESS'
export const SEND_CONTACT_FORM_ERROR = 'SEND_CONTACT_FORM_ERROR'

//MESSAGES
export const SUCCESS_MESSAGE = 'SUCCESS_MESSAGE'
export const ERROR_MESSAGE = 'ERROR_MESSAGE'
export const INFO_MESSAGE = 'INFO_MESSAGE'
export const SET_MESSAGE = 'SET_MESSAGE'
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE'

// ORDER
export const LIST_ORDERS = 'LIST_ORDERS'
export const NEW_ORDER = 'NEW_ORDER'
export const NEW_ORDER_SUCCESS = 'NEW_ORDER_SUCCESS'
export const NEW_ORDER_ERROR = 'NEW_ORDER_ERROR'

//PRODUCTS
export const ADD_PRODUCT = 'ADD_PRODUCT'
export const DELETE_PRODUCT = 'DELETE_PRODUCT'
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT'
export const FETCH_PRODUCTS = ' FETCH_PRODUCTS'
export const FETCH_PRODUCTS_SUCCESS = ' FETCH_PRODUCTS_SUCCESS'
export const FETCH_PRODUCTS_ERROR = ' FETCH_PRODUCTS_ERROR'

//USER
export const FETCH_USER_DETAILS = 'FETCH_USER_DETAILS'
export const FETCH_USER_DETAILS_SUCCESS = 'FETCH_USER_DETAILS_SUCCESS'
export const FETCH_USER_DETAILS_ERROR = 'FETCH_USER_DETAILS_ERROR'
export const REQUEST_CHANGE_USER_DETAILS = 'REQUEST_CHANGE_USER_DETAILS'
export const REQUEST_CHANGE_USER_DETAILS_SUCCESS = 'REQUEST_CHANGE_USER_DETAILS_SUCCESS'
export const REQUEST_CHANGE_USER_DETAILS_ERROR = 'REQUEST_CHANGE_USER_DETAILS_ERROR'
export const CLEAR_USER_DETAILS = 'CLEAR_USER_DETAILS'
